
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'NFS SLASH WORDstart : NFS WORD pathpath : SLASH WORD path\n            | emptyempty :'
    
_lr_action_items = {'NFS':([0,],[2,]),'$end':([1,3,4,6,7,8,],[0,-4,-1,-3,-4,-2,]),'WORD':([2,5,],[3,7,]),'SLASH':([3,7,],[5,5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[1,]),'path':([3,7,],[4,8,]),'empty':([3,7,],[6,6,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> NFS WORD path','start',3,'p_start','ply_parser.py',26),
  ('path -> SLASH WORD path','path',3,'p_path','ply_parser.py',35),
  ('path -> empty','path',1,'p_path','ply_parser.py',36),
  ('empty -> <empty>','empty',0,'p_empty','ply_parser.py',43),
]
