
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'NAME NFS SLASHstart : NFS NAME SLASH NAME SLASH restrest : segment rest\n            | emptysegment : NAME\n               | NAME SLASHempty :'
    
_lr_action_items = {'NFS':([0,],[2,]),'$end':([1,6,7,8,9,10,11,12,],[0,-6,-4,-1,-6,-3,-5,-2,]),'NAME':([2,4,6,7,9,11,],[3,5,7,-4,7,-5,]),'SLASH':([3,5,7,],[4,6,11,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[1,]),'rest':([6,9,],[8,12,]),'segment':([6,9,],[9,9,]),'empty':([6,9,],[10,10,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> NFS NAME SLASH NAME SLASH rest','start',6,'p_start','ply_parser.py',39),
  ('rest -> segment rest','rest',2,'p_rest','ply_parser.py',47),
  ('rest -> empty','rest',1,'p_rest','ply_parser.py',48),
  ('segment -> NAME','segment',1,'p_segment','ply_parser.py',55),
  ('segment -> NAME SLASH','segment',2,'p_segment','ply_parser.py',56),
  ('empty -> <empty>','empty',0,'p_empty','ply_parser.py',63),
]
